# Minimal Docker Compose for testing cross-platform compatibility
# This version excludes Ollama and other optional services for faster testing

services:
  web:
    build: .
    image: jps-prospect-aggregate:latest
    container_name: jps-web
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://jps_user:${DB_PASSWORD}@db:5432/jps_prospects
      - USER_DATABASE_URL=postgresql://jps_user:${DB_PASSWORD}@db:5432/jps_users
      - SECRET_KEY=${SECRET_KEY}
      - FILE_FRESHNESS_SECONDS=86400
      - ENABLE_LLM_ENHANCEMENT=False  # Disable LLM for testing
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jps-network

  db:
    image: postgres:15-alpine
    container_name: jps-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=jps_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=jps_prospects
      - POSTGRES_MULTIPLE_DATABASES=jps_prospects,jps_users
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    entrypoint: >
      sh -c "
        docker-entrypoint.sh postgres &
        sleep 15 &&
        until pg_isready -U jps_user -d postgres; do sleep 1; done &&
        psql -U jps_user -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'jps_prospects'\" | grep -q 1 || psql -U jps_user -d postgres -c \"CREATE DATABASE jps_prospects\" &&
        psql -U jps_user -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'jps_users'\" | grep -q 1 || psql -U jps_user -d postgres -c \"CREATE DATABASE jps_users\" &&
        echo 'Databases created successfully' &&
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jps_user -d jps_prospects"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jps-network

volumes:
  postgres_data:

networks:
  jps-network:
    driver: bridge