"""Add enhancement status fields to prospects

Revision ID: 3c1daf8e563b
Revises: 20e4b47362d1
Create Date: 2025-06-17 19:01:43.698568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1daf8e563b'
down_revision = '20e4b47362d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhancement_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('enhancement_started_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('enhancement_user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_estimated_value_single'))
        batch_op.drop_index(batch_op.f('idx_naics_source'))
        batch_op.drop_index(batch_op.f('idx_ollama_processed_at'))
        batch_op.drop_index(batch_op.f('idx_primary_contact_email'))
        batch_op.create_index(batch_op.f('ix_prospects_agency'), ['agency'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_enhancement_started_at'), ['enhancement_started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_enhancement_status'), ['enhancement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_enhancement_user_id'), ['enhancement_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_estimated_value_single'), ['estimated_value_single'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_naics_source'), ['naics_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_ollama_processed_at'), ['ollama_processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_place_city'), ['place_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_place_state'), ['place_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_primary_contact_email'), ['primary_contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospects_title'))
        batch_op.drop_index(batch_op.f('ix_prospects_primary_contact_email'))
        batch_op.drop_index(batch_op.f('ix_prospects_place_state'))
        batch_op.drop_index(batch_op.f('ix_prospects_place_city'))
        batch_op.drop_index(batch_op.f('ix_prospects_ollama_processed_at'))
        batch_op.drop_index(batch_op.f('ix_prospects_naics_source'))
        batch_op.drop_index(batch_op.f('ix_prospects_estimated_value_single'))
        batch_op.drop_index(batch_op.f('ix_prospects_enhancement_user_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_enhancement_status'))
        batch_op.drop_index(batch_op.f('ix_prospects_enhancement_started_at'))
        batch_op.drop_index(batch_op.f('ix_prospects_description'))
        batch_op.drop_index(batch_op.f('ix_prospects_agency'))
        batch_op.create_index(batch_op.f('idx_primary_contact_email'), ['primary_contact_email'], unique=False)
        batch_op.create_index(batch_op.f('idx_ollama_processed_at'), ['ollama_processed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_naics_source'), ['naics_source'], unique=False)
        batch_op.create_index(batch_op.f('idx_estimated_value_single'), ['estimated_value_single'], unique=False)
        batch_op.drop_column('enhancement_user_id')
        batch_op.drop_column('enhancement_started_at')
        batch_op.drop_column('enhancement_status')

    # ### end Alembic commands ###
