"""Add scraper_key to DataSource model

Revision ID: 4627cb27031b
Revises: d1def2efebc3
Create Date: 2024-07-16 14:51:39.597019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4627cb27031b'
down_revision = 'd1def2efebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraper_key', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_sources_scraper_key'), ['scraper_key'], unique=False)

    # ### end Alembic commands ###

    # Populate scraper_key for existing data
    bind = op.get_bind()
    Session = sa.orm.sessionmaker(bind=bind)
    session = Session()

    data_source_updates = [
        {"name": "Acquisition Gateway", "scraper_key": "acq_gateway"},
        {"name": "Department of Commerce", "scraper_key": "doc"},
        {"name": "Department of Homeland Security", "scraper_key": "dhs"},
        {"name": "Department of Justice", "scraper_key": "doj"},
        {"name": "Department of State", "scraper_key": "dos"},
        {"name": "Department of Health and Human Services", "scraper_key": "hhs"},
        {"name": "Social Security Administration", "scraper_key": "ssa"},
        {"name": "Treasury Forecast", "scraper_key": "treasury"},
        {"name": "DOT Forecast", "scraper_key": "dot"},
        # Add other specific mappings if they exist by different names in the DB
    ]

    for update_info in data_source_updates:
        op.execute(
            sa.text("UPDATE data_sources SET scraper_key = :scraper_key WHERE name = :name AND scraper_key IS NULL")
            .bindparams(scraper_key=update_info["scraper_key"], name=update_info["name"])
        )
    
    session.commit()
    session.close()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_scraper_key'))
        batch_op.drop_column('scraper_key')

    # ### end Alembic commands ###
