"""Add ai_enhanced_title field to prospects table

Revision ID: 5fb5cc7eff5b
Revises: fbc0e1fbf50d
Create Date: 2025-06-03 19:21:41.711762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb5cc7eff5b'
down_revision = 'fbc0e1fbf50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('ai_enhanced_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'ai_enhanced_title')
    # ### end Alembic commands ###
