"""Add records_found and error_message to ScraperStatus

Revision ID: 8d8b7ee0b3ea
Revises: merge_final_and_align
Create Date: 2025-09-15 15:14:14.399748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8b7ee0b3ea'
down_revision = 'merge_final_and_align'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inferred_prospect_data',
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('inferred_requirement_title', sa.Text(), nullable=True),
    sa.Column('inferred_requirement_description', sa.Text(), nullable=True),
    sa.Column('inferred_naics', sa.String(), nullable=True),
    sa.Column('inferred_naics_description', sa.String(length=200), nullable=True),
    sa.Column('inferred_estimated_value', sa.Float(), nullable=True),
    sa.Column('inferred_est_value_unit', sa.String(), nullable=True),
    sa.Column('inferred_estimated_value_min', sa.Float(), nullable=True),
    sa.Column('inferred_estimated_value_max', sa.Float(), nullable=True),
    sa.Column('inferred_solicitation_date', sa.Text(), nullable=True),
    sa.Column('inferred_award_date', sa.Text(), nullable=True),
    sa.Column('inferred_place_city', sa.Text(), nullable=True),
    sa.Column('inferred_place_state', sa.Text(), nullable=True),
    sa.Column('inferred_place_country', sa.Text(), nullable=True),
    sa.Column('inferred_contract_type', sa.Text(), nullable=True),
    sa.Column('inferred_set_aside', sa.Text(), nullable=True),
    sa.Column('inferred_primary_contact_email', sa.String(length=100), nullable=True),
    sa.Column('inferred_primary_contact_name', sa.String(length=100), nullable=True),
    sa.Column('llm_confidence_scores', sa.JSON(), nullable=True),
    sa.Column('inferred_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('inferred_by_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('prospect_id')
    )
    with op.batch_alter_table('scraper_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_found', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_status', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('records_found')

    op.drop_table('inferred_prospect_data')
    # ### end Alembic commands ###
