"""Add FileProcessingLog table for intelligent data retention

Revision ID: add_file_processing_log_table
Revises: 20e4b47362d1
Create Date: 2025-06-19 15:18:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_file_processing_log_table'
down_revision = '3c1daf8e563b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processing_completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('schema_columns', sa.JSON(), nullable=True),
    sa.Column('schema_issues', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_processing_logs_file_name'), 'file_processing_logs', ['file_name'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_file_path'), 'file_processing_logs', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_file_timestamp'), 'file_processing_logs', ['file_timestamp'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_processing_completed_at'), 'file_processing_logs', ['processing_completed_at'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_processing_started_at'), 'file_processing_logs', ['processing_started_at'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_source_id'), 'file_processing_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_file_processing_logs_success'), 'file_processing_logs', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_processing_logs_success'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_source_id'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_processing_started_at'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_processing_completed_at'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_file_timestamp'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_file_path'), table_name='file_processing_logs')
    op.drop_index(op.f('ix_file_processing_logs_file_name'), table_name='file_processing_logs')
    op.drop_table('file_processing_logs')
    # ### end Alembic commands ###