"""Revert Proposal to Prospect model and table name

Revision ID: d1def2efebc3
Revises: 
Create Date: 2025-05-19 09:04:02.585739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1def2efebc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('data_sources',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('url', sa.String(), nullable=True),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('last_scraped', sa.TIMESTAMP(timezone=True), nullable=True),
    # sa.Column('frequency', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('data_sources', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_data_sources_name'), ['name'], unique=True)

    # op.create_table('scraper_status',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('source_id', sa.Integer(), nullable=False),
    # sa.Column('status', sa.String(), nullable=True),
    # sa.Column('last_checked', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    # sa.Column('details', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('scraper_status', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_scraper_status_source_id'), ['source_id'], unique=False)

    with op.batch_alter_table('inferred_prospect_data', schema=None) as batch_op:
        batch_op.drop_column('inferred_office')

    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agency', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_prospects_solicitation_date')
        batch_op.drop_index('ix_prospects_source')
        batch_op.create_index(batch_op.f('ix_prospects_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key('fk_prospects_source_id_data_sources', 'data_sources', ['source_id'], ['id'])
        batch_op.drop_column('requirement_title')
        batch_op.drop_column('source')
        batch_op.drop_column('solicitation_date')
        batch_op.drop_column('requirement_description')
        batch_op.drop_column('office')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('requirement_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('solicitation_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('requirement_title', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_prospects_source_id_data_sources', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prospects_source_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_release_date'))
        batch_op.create_index('ix_prospects_source', ['source'], unique=False)
        batch_op.create_index('ix_prospects_solicitation_date', ['solicitation_date'], unique=False)
        batch_op.drop_column('source_id')
        batch_op.drop_column('release_date')
        batch_op.drop_column('agency')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('inferred_prospect_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inferred_office', sa.TEXT(), nullable=True))

    # with op.batch_alter_table('scraper_status', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_scraper_status_source_id'))

    # op.drop_table('scraper_status')
    # with op.batch_alter_table('data_sources', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_data_sources_name'))

    # op.drop_table('data_sources')
    # ### end Alembic commands ###
