"""Revert Proposal to Prospect model and table name

Revision ID: d1def2efebc3
Revises: 
Create Date: 2025-05-19 09:04:02.585739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1def2efebc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was designed for existing databases, not fresh installations
    # Check if tables exist before attempting to modify them
    
    from alembic import context
    
    # Get connection to check table existence
    connection = context.get_bind()
    
    # Check if inferred_prospect_data table exists
    result = connection.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'inferred_prospect_data')"
    )).fetchone()
    
    if result and result[0]:  # Table exists
        print("inferred_prospect_data table exists, dropping inferred_office column")
        with op.batch_alter_table('inferred_prospect_data', schema=None) as batch_op:
            batch_op.drop_column('inferred_office')
    else:
        print("inferred_prospect_data table does not exist, skipping column drop")

    # Check if prospects table exists
    result = connection.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'prospects')"
    )).fetchone()
    
    if result and result[0]:  # Table exists
        print("prospects table exists, performing modifications")
        with op.batch_alter_table('prospects', schema=None) as batch_op:
            # Check if columns already exist before adding them
            batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('agency', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
            
            # Try to drop indexes, but don't fail if they don't exist
            try:
                batch_op.drop_index('ix_prospects_solicitation_date')
            except Exception as e:
                print(f"Index ix_prospects_solicitation_date not found: {e}")
            
            try:
                batch_op.drop_index('ix_prospects_source')
            except Exception as e:
                print(f"Index ix_prospects_source not found: {e}")
            
            batch_op.create_index(batch_op.f('ix_prospects_release_date'), ['release_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_prospects_source_id'), ['source_id'], unique=False)
            batch_op.create_foreign_key('fk_prospects_source_id_data_sources', 'data_sources', ['source_id'], ['id'])
            
            # Try to drop columns, but don't fail if they don't exist
            try:
                batch_op.drop_column('requirement_title')
            except Exception as e:
                print(f"Column requirement_title not found: {e}")
            
            try:
                batch_op.drop_column('source')
            except Exception as e:
                print(f"Column source not found: {e}")
            
            try:
                batch_op.drop_column('solicitation_date')
            except Exception as e:
                print(f"Column solicitation_date not found: {e}")
            
            try:
                batch_op.drop_column('requirement_description')
            except Exception as e:
                print(f"Column requirement_description not found: {e}")
            
            try:
                batch_op.drop_column('office')
            except Exception as e:
                print(f"Column office not found: {e}")
    else:
        print("prospects table does not exist, skipping modifications")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('requirement_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('solicitation_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('requirement_title', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_prospects_source_id_data_sources', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prospects_source_id'))
        batch_op.drop_index(batch_op.f('ix_prospects_release_date'))
        batch_op.create_index('ix_prospects_source', ['source'], unique=False)
        batch_op.create_index('ix_prospects_solicitation_date', ['solicitation_date'], unique=False)
        batch_op.drop_column('source_id')
        batch_op.drop_column('release_date')
        batch_op.drop_column('agency')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('inferred_prospect_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inferred_office', sa.TEXT(), nullable=True))

    # with op.batch_alter_table('scraper_status', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_scraper_status_source_id'))

    # op.drop_table('scraper_status')
    # with op.batch_alter_table('data_sources', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_data_sources_name'))

    # op.drop_table('data_sources')
    # ### end Alembic commands ###
